### PR TITLE
Rootless 

### LINKED ISSUE #115: Rootless support for Dragon
With Fugu15Max and Palera1n 2.0 around the corner, I guess one should look into Dragon supporting building rootless packages

### PR DESCRIPTION
**Pull request by L1ghtmann**
Resolves #115

Relies on:
- https://github.com/DragonBuild/lib/pull/2
- https://github.com/DragonBuild/frameworks/pull/2

Please note:
- We are now switching to the use of `@rpath` as it has been available since iOS 8 (?) and we don't provide support for lower targets
  - As such, as libs'/frameworks' install-name's have been modified as have the relevant project types' (e.g., tweaks, dylibs, bundles, frameworks) install-names
- Theos support is *slightly* jank as the control file is edited in-place in the staging dir as #114 has not been implemented yet
  - I *may* give this a go, but I am largely unfamiliar with our Makefile parser

### CODE REVIEW

**Comment by L1ghtmann** [comment]
Also, I noticed while implementing the install-name changes that we have both `lopts` and `ldflags`. Is there a reason we have two vars that seemingly serve the same purpose?

**Comment by TheGithubJoshua** [comment]
+1 for this also if this gets merged what are the arguments to build for rootless?

**Comment by L1ghtmann** [comment]
Hey, thanks! You'd pass `ro` or `rootless` along with your build command. Updates coming to the help page as well (see my open prs).

**Comment by 0cyn** [comment]
> Also, I noticed while implementing the install-name changes that we have both lopts and ldflags. Is there a reason we have two vars that seemingly serve the same purpose? typeldflags seems to be available for specific use cases.

There are a lot of things in this project implemented like 3-4 years ago where there was probably a good reason once, but absolutely nobody knows what it was anymore and it's no longer relevant.

**Pull request merged**
